### ISSUE TITLE
[BUG] 1.18.2 Error getting player inventory over NMS

### ISSUE THREAD

**Issue by jonaas13** [brunyman/MPDB#70]
Getting this error on 1.18.2 
```PowerShell
[19:41:15 WARN]: [MysqlPlayerDataBridge] Error getting player inventory over NMS on player Disconnect, getting it over Spigot API instead. Player: jonaas13 Error: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null
```

**Comment by OshinoLin** [comment]
same problem
[MysqlPlayerDataBridge] Error getting player inventory over NMS on player Disconnect, getting it over Spigot API instead. Player: CMXKA1030 Error: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null

**Comment by Blautee** [comment]
same problem when trying to /restart or /stop while players are still on the 1.18.2 server. this error comes after the "MysqlPlayerDataBridge] Saving data and kicking all players..." message:

[12:18:41 ERROR]: Could not pass event PlayerCommandPreprocessEvent to MysqlPlayerDataBridge v4.2.0
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null

**Comment by jonaas13** [comment]
@brunyman any eta for an update on the plugin?

**Comment by Blautee** [comment]
since this error only occurs on one of my two servers in my bungee network, maybe we can find a workaround for this. i have tried changing the servers name in the server.properies because that was the first thing that came to my mind. it didn't help tho. i'm also running paper and tried spigot as an alternative, but i couldn't quite get the server to run somehow. but i guess there must be something triggering this error, that maybe can be fixed on our side. do you have any ideas for a workaround @jonaas13 :D

**Comment by jonaas13** [comment]
@Blautee I'm also having the kick issue, not on all servers though. A simple kick all command will fix the kick issue. 
Although I haven't found a workaround yet for other issues with 1.18.2
I believe it's version related, plugin just needs to be updated.
